# Generated by Django 4.2 on 2023-04-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_datecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='important',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], max_length=1),
        ),
    ]
